baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "RainbowCake"
theme = "learn"
# themesdir = "../.."
#pygmentsCodeFences = true
#pygmentsStyle = "monokailight"

#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir= false
#enableMissingTranslationPlaceholders = false


[params]
author = "MÃ¡rton Braun"
disableSearch = false
disableInlineCopyToClipBoard = true
disableLanguageSwitchingButton = true
themeVariant = "green"
disableShortcutsTitle = true

[outputs]
home = [ "HTML", "JSON" ]


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub repo"
url = "https://github.com/rainbowcake/rainbowcake"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Android Studio Templates"
weight = 20
url = "https://github.com/rainbowcake/rainbowcake-templates"
