baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "RainbowCake"
theme = "learn"
# themesdir = "../.."
#pygmentsCodeFences = true
#pygmentsStyle = "monokailight"

#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir= false
#enableMissingTranslationPlaceholders = false


[params]
author = "MÃ¡rton Braun"
disableSearch = false
disableInlineCopyToClipBoard = true
disableLanguageSwitchingButton = true
themeVariant = "green"
disableShortcutsTitle = true

[outputs]
home = [ "HTML", "JSON" ]


[[menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> GitLab repo"
url = "https://gitlab.autsoft.hu/AutSoft/AndroidChapter/rainbow-cake/rainbow-cake"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> Android Studio Templates"
weight = 20
url = "https://gitlab.autsoft.hu/AutSoft/AndroidChapter/rainbow-cake/rainbow-cake-templates"

[[menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> Sample apps"
url = "https://gitlab.autsoft.hu/AutSoft/AndroidChapter/rainbow-cake/demos"
weight = 30
